version: "3.8"

services:

  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
  
  elasticsearch:
    container_name: "elasticsearch"
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.12.0"
    container_name: "kibana"
  
  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6379:6379"
    